### ISSUE TITLE
🪲 Sometimes `cppyy` converts a `std::int16_t` into an `int`

### ISSUE THREAD

**Issue by lukevalenty** [wlav/cppyy#265]
I discovered another issue where sometimes `std::int16_t` or other integer types get converted to an `int`. This doesn't always happen. I'm using a similar test case as I previously showed you, but this time with a variety of integral types as list elements:

```python
import hypothesis
from hypothesis import given, settings, example, note, event, strategies as st
import cppyy
import pytest

cppyy.include("limits")

cppyy.cppdef("""
    namespace test {
    template <typename T>
    constexpr std::size_t tuple_size(const T&) {
        return std::tuple_size<T>::value;
    }
    constexpr bool as_bool(bool b) {
        return static_cast<bool>(b);
    }
    template<typename... Ts>
    struct list {
        template<typename... Us>
        constexpr auto operator==(list<Us...>) const -> bool {
            return false;
        }
        constexpr auto operator==(list<Ts...>) const -> bool {
            return true;
        }
    };
    template<typename... Ts>
    constexpr auto make_list(Ts...) {
        return list<Ts...>{};
    }
    template<typename... Ls, typename... Rs>
    constexpr auto cat(list<Ls...>, list<Rs...>) {
        return list<Ls..., Rs...>{};
    }
    } // namespace test
""")

std = cppyy.gbl.std
test = cppyy.gbl.test

bools = st.booleans().map(lambda v: test.as_bool(v))

def make_c_type_strat(t):
    min_val = std.numeric_limits[t].min()
    max_val = std.numeric_limits[t].max()
    return st.integers(min_value=int(min_val), max_value=int(max_val)).map(lambda v: t(v))

int16s = make_c_type_strat(std.int16_t)
int32s = make_c_type_strat(std.int32_t)
int64s = make_c_type_strat(std.int64_t)

uint16s = make_c_type_strat(std.uint16_t)
uint32s = make_c_type_strat(std.uint32_t)
uint64s = make_c_type_strat(std.uint64_t)

cpp_primitives = st.one_of(bools, int16s, int32s, int64s, uint16s, uint32s, uint64s)

def as_test_list_tree(value):
    if isinstance(value, list):
        values = [as_test_list_tree(v) for v in value]
        return test.make_list(*values)
    else:
        return value

@st.composite
def py_list_trees(draw, leaves=cpp_primitives):
    t = draw(st.recursive(leaves, lambda children: st.lists(children)))

    if not isinstance(t, list):
        t = [t]

    return t

@settings(deadline=2000, max_examples=100)
@given(py_list_trees(), py_list_trees())
@example([0], [[], []])

# these three examples fail
@example([test.as_bool(False)],[std.int16_t(0)])
@example([std.int16_t(0)], [test.as_bool(False)])
@example([std.int16_t(0)], [std.int16_t(0)])

# these two examples don't fail for some reason
@example([std.int16_t(0)], [])
@example([], [std.int16_t(0)])

def test_list_cat(pytestconfig, left, right):
    expected = as_test_list_tree(left + right)
    actual = test.cat(as_test_list_tree(left), as_test_list_tree(right))
    assert actual == expected
```

Here's the full output from running this test:

```
(venv_tvargs_dev) lvalenty@Zenbook:~/cppyy_tvargs_dev$ python -m pytest -sv test_stress_cat_list.py --hypothesis-show-statistics
=========================================================== test session starts ============================================================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0 -- /home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/home/lvalenty/cppyy_tvargs_dev/.hypothesis/examples'))
rootdir: /home/lvalenty/cppyy_tvargs_dev
plugins: forked-1.6.0, hypothesis-6.112.2
collecting ... error: Problems loading PCH: '/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/cppyy/allDict.cxx.pch.6.30.0'.
collected 1 item

test_stress_cat_list.py::test_list_cat FAILED

================================================================= FAILURES =================================================================
______________________________________________________________ test_list_cat _______________________________________________________________
  + Exception Group Traceback (most recent call last):
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
  |     result: TResult | None = func()
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/runner.py", line 242, in <lambda>
  |     lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
  |     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 182, in _multicall
  |     return outcome.get_result()
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_result.py", line 100, in get_result
  |     raise exc.with_traceback(exc.__traceback__)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
  |     teardown.throw(outcome._exception)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/threadexception.py", line 92, in pytest_runtest_call
  |     yield from thread_exception_runtest_hook()
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/threadexception.py", line 68, in thread_exception_runtest_hook
  |     yield
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
  |     teardown.throw(outcome._exception)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/unraisableexception.py", line 95, in pytest_runtest_call
  |     yield from unraisable_exception_runtest_hook()
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/unraisableexception.py", line 70, in unraisable_exception_runtest_hook
  |     yield
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
  |     teardown.throw(outcome._exception)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/logging.py", line 846, in pytest_runtest_call
  |     yield from self._runtest_for(item, "call")
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/logging.py", line 829, in _runtest_for
  |     yield
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
  |     teardown.throw(outcome._exception)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/capture.py", line 880, in pytest_runtest_call
  |     return (yield)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 167, in _multicall
  |     teardown.throw(outcome._exception)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/skipping.py", line 257, in pytest_runtest_call
  |     return (yield)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
  |     res = hook_impl.function(*args)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/runner.py", line 174, in pytest_runtest_call
  |     item.runtest()
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/python.py", line 1627, in runtest
  |     self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
  |     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
  |     raise exception.with_traceback(exception.__traceback__)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
  |     res = hook_impl.function(*args)
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/_pytest/python.py", line 159, in pytest_pyfunc_call
  |     result = testfunction(**testargs)
  |   File "/home/lvalenty/cppyy_tvargs_dev/test_stress_cat_list.py", line 98, in test_list_cat
  |     @given(py_list_trees(), py_list_trees())
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/hypothesis/core.py", line 1661, in wrapped_test
  |     _raise_to_user(errors, state.settings, [], " in explicit examples")
  |   File "/home/lvalenty/cppyy_tvargs_dev/venv_tvargs_dev/lib/python3.10/site-packages/hypothesis/core.py", line 1365, in _raise_to_user
  |     raise the_error_hypothesis_found
  | exceptiongroup.ExceptionGroup: Hypothesis found 3 distinct failures in explicit examples. (3 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/lvalenty/cppyy_tvargs_dev/test_stress_cat_list.py", line 109, in test_list_cat
    |     assert actual == expected
    | AssertionError: assert <cppyy.gbl.te...x5605c05311a0> == <cppyy.gbl.te...x5605c0485260>
    |
    |   Full diff:
    |   - <cppyy.gbl.test.list<bool,short> object at 0x5605c0485260>
    |   ?                           ^^^^                     -- ^^
    |   + <cppyy.gbl.test.list<bool,int> object at 0x5605c05311a0>
    |   ?                           ^^                      ^^^^
    | Falsifying explicit example: test_list_cat(
    |     pytestconfig=<_pytest.config.Config object at 0x7f8ad78aac50>,
    |     left=[False],
    |     right=[0],
    | )
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/home/lvalenty/cppyy_tvargs_dev/test_stress_cat_list.py", line 109, in test_list_cat
    |     assert actual == expected
    | AssertionError: assert <cppyy.gbl.te...x5605c0460190> == <cppyy.gbl.te...x5605bdaeaaa0>
    |
    |   Full diff:
    |   - <cppyy.gbl.test.list<short,bool> object at 0x5605bdaeaaa0>
    |   ?                      ^^^^                        ^^^^^^^
    |   + <cppyy.gbl.test.list<int,bool> object at 0x5605c0460190>
    |   ?                      ^^                        ^^^^^^^
    | Falsifying explicit example: test_list_cat(
    |     pytestconfig=<_pytest.config.Config object at 0x7f8ad78aac50>,
    |     left=[0],
    |     right=[False],
    | )
    +---------------- 3 ----------------
    | Traceback (most recent call last):
    |   File "/home/lvalenty/cppyy_tvargs_dev/test_stress_cat_list.py", line 109, in test_list_cat
    |     assert actual == expected
    | AssertionError: assert <cppyy.gbl.te...x5605bdaea280> == <cppyy.gbl.te...x5605c0550b60>
    |
    |   Full diff:
    |   - <cppyy.gbl.test.list<short,short> object at 0x5605c0550b60>
    |   ?                      ^^^^  ^^^^                   ----- ^
    |   + <cppyy.gbl.test.list<int,int> object at 0x5605bdaea280>
    |   ?                      ^^  ^^                    ^^^^^^
    | Falsifying explicit example: test_list_cat(
    |     pytestconfig=<_pytest.config.Config object at 0x7f8ad78aac50>,
    |     left=[0],
    |     right=[0],
    | )
    +------------------------------------
========================================================== Hypothesis Statistics ===========================================================
========================================================= short test summary info ==========================================================
FAILED test_stress_cat_list.py::test_list_cat - exceptiongroup.ExceptionGroup: Hypothesis found 3 distinct failures in explicit examples. (3 sub-exceptions)
============================================================ 1 failed in 1.20s =============================================================
```

Sorry to pester you with these bugs...I was actually a validation engineer for most of my career! 😅 I am extremely excited to leverage cppyy and hypothesis to test several of our open source libraries...it's such a powerful capability...there really is no other way to do it.

**Comment by wlav** [comment]
`std.int16_t` is a class (that yes, exists purely for template type labeling) that is derived from `int` (to allow it to be used everywhere in Python where an `int` is expected). What is going on here is that if a prior call instantiated a template with `int` type, then it is considered a fair match to use with `std.int16_t`, rather than instantiating a new function. If no such function exists yet, instantiation will happen with `short`. Note that calls with a Python `int` will continue to match that function taking a `short` until the value overflows, in which case the larger C++ `int` type gets instantiated.

So first, the test is going to get a lot further by using `ctypes.c_int16` (which is an explicit type, not derived from Python `int`) instead of `std.int16_t` (which also means that `std.int16_t` could be handled more strictly than it currently is).

But then, I do eventually see values that are too large too fit, followed by automatic increases in chosen template argument, followed by a type mismatch. I'm not sure whether I'm reading the test wrong here (as it shouldn't based on the use of limits), but that's a consequence again of choosing to derive from Python's `int` v.s. having a different type. Compare these:

```
>>> ctypes.c_int16(2**32)
c_short(0)
>>> cppyy.gbl.std.int16_t(2**32)
4294967296
>>> 
```

As a design choice, this is mostly attempting to minimize surprise. `ctypes` side-steps that by forcing you to explicitly access the underlying using `value`, which is a Python `int`, but folks disliked that indirection. But then if the result is being used in straight up Python calculations, it really should behave like a Python `int`.

Aside, `numpy` "solves" it by reimplementing a complete number system, instead of using Python's builtins. So if e.g. I do something like `2**32 * np.int16(4)`, then the resulting type is an `np.int64`. However ... there, too, the limiting case of `type(2**64 * np.int16(4))` will give you a Python `int`, thus leaving the `numpy` number system and then there's no going back, unless explicitly.

That's a lot of text for saying yes, improvements are possible (in particular for template instantiations; esp. since`int8_t` and `uint8_t` already treated as special cases for different reasons and upstream is working on this), but no, it'll never be an exact match as the target audience is Python programmers, not C++ ones.

Okay, so now what if you are indeed a C++ programmer? Well, you can actually side-step all the heuristics and guesswork where cppyy is trying to balance different use cases across 20 years of history, by being explicit:
```
        return test.make_list[tuple(type(v) for v in values)](*values)
```

**Comment by lukevalenty** [comment]
> `return test.make_list[tuple(type(v) for v in values)](*values)`

I'll give this a try. Thanks for the explanation!

**Comment by lukevalenty** [comment]
That did the trick, thank you!
