### ISSUE TITLE
No module named '_cppyy' on PyPy windows

### ISSUE THREAD

**Issue by Marvisak** [wlav/cppyy#43]
I am using windows 10 64bit with PyPy, I installed cppyy using pip, when I try to import cppyy I get this error
```
>>>> import cppyy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\pypy\lib\site-packages\cppyy\__init__.py", line 78, in <module>
    from ._pypy_cppyy import *
  File "D:\pypy\lib\site-packages\cppyy\_pypy_cppyy.py", line 33, in <module>
    import _cppyy as _backend     # built-in module
ModuleNotFoundError: No module named '_cppyy'
```
This happens with all versions of PyPy (3.9, 3.8...), when I tried to use wsl it worked, but I don't think that's ideal.
I know there is #1 but that is a year old issue and I don't know if it was fixed and it's just me having problems or it's still doing this.

Thanks for any answer

**Comment by wlav** [comment]
Still not fixed. I need to make some changes to enable the tests for upstream to run, then they can add it. I now do have Windows running through VirtualBox on a beefy Linux machine, so could try to build PyPy, but haven't gotten around to it yet.
